name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Checkout & Setup Node.js
    runs-on: ubuntu-latest
    outputs:
      yarn-cache: ${{ steps.cache-yarn.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.0
      - name: Cache Yarn dependencies
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
  
  install-dependencies:
    name: Install dependencies
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn install --frozen-lockfile

  type-check:
    name: Check TypeScript types
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: TypeScript Type Check
        run: yarn type-check

  build:
    name: Build the app
    needs:
      - install-dependencies
      - type-check
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: yarn build
