name: CI/CD for Gym Logs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js with caching
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.0
          cache: "yarn"

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile 

      # 4. Check types
      - name: Check TypeScript types
        run: yarn types

      # 5. Build the project
      - name: Build the app
        run: yarn build
