name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js with caching
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.0
          cache: "yarn"

      # 3. Cache Yarn dependencies
      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 4. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 5. Check types
      - name: Check TypeScript types
        run: yarn types

      # 6. Build the project
      - name: Build the app
        run: yarn build
